runtime: java15
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/cloudrun/placeholder
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west9
    gcb-trigger-id: 4d8b515c-c0af-43cc-a20f-e0752036fe31
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: watashi-house
  namespace: '66688633686'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
      name: watashi-house-placeholder
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/cloudrun/placeholder
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: 66688633686-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
